### ISSUE TITLE
updated ESAS species coding

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#97]
Please add or adjust the following to the ESAS coding list:
![image](https://user-images.githubusercontent.com/7381853/175934683-45f459d6-4044-43a9-9325-aa0e334e4b02.png)
![image](https://user-images.githubusercontent.com/7381853/175934729-3055eb0e-bbcc-4b5d-b443-ff8189a47229.png)

**Comment by peterdesmet** [comment]
@cmspinto or @Osanna123 this issue requests updates to the species list in the database:

- [ ] Add a new taxon `126`, cf. https://github.com/ices-tools-dev/esas/commit/290ece350197cb24f46d86b156420929318f6018
```yaml
esas_code: 126
scientific_name: Podiceps grisegena / auritus
english_name: Red-necked / Slavonian Grebe
euring_code:
euring_scientific_name:
aphia_id: 137056
aphia_scientific_name: Podiceps
remarks: 
```

- [ ] Update taxon `6169` to `6159`, cf. https://github.com/ices-tools-dev/esas/commit/e480f3f9b2dca2eab5a3bf1d7d3613dd18b29c83

```yaml
esas_code: 6159 # not 6169
scientific_name: Sterna hirundo / paradisaea
english_name: Common / Arctic Tern
euring_code: 06159 # new
euring_scientific_name: Sterna hirundo/paradisaea # new
aphia_id: 137047
aphia_scientific_name: Sterna
remarks: 
```

@nicolasvanermen rather than screenshots, it is easier if you (also) include the URL to the commit in the issue.
